before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: dUsyvViMNQundkMz1HjITe1l7cLUz7lvne6c6Ai8YKhD5Nx6sJKRIpMITjm1I3P2nXhn3dCNMIn59OmtxSvj0bubrTcjN8B7PxBPHoq1cfA8Fx+lc6Eb0w/98HGfO03cQOXrXtEfJU3mH45b5BlxXVL+B6iTkpIaiRis/svzLacenY7XJisM5hQeOS1D6BbNhzWJVy/zU4rNCoTVJl8nPsTn5SfYEqk3QuflSdcljG2MIG4td1RbuRqQylMV7QEgzKjJlg2yh1vTRqZY9Gc+OkxBt2x+ohzRMk0YShno44loEq+0Y30WW2PrOtxIlj4avT8s9/gFN3cBgCav+uXmWi7ypS07wMU+BTuydrk7yc6btnKaB5IBCbTsc1VswFnRs5IWoHMklvMI64SvXayBc7NBHS4yrc7q1tkc5qp4tlIzvh6cKWw0Zx3THQzFPPLPkMncA10pDhIkOSy/wOie7QueMcoxLHhPH8txLmnA6SZmFbcGqWhbCC3UxauuxqcHj0Jd3i+3SaS98bpJjdvtwO0t9sOS+1JCdb7Ptygp20NsLjpodr1w+/31gre5DOLqZuVjZUxCmqNY3wvi5UefE+mqGVOtoOY0/AVSsAgQdnjGgjfAJ2xdXiM2sGA6jjXx4cC7gFnzrnJga80Pqy6t9sPDT8ftVLdvOSH54YzZ4YE= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
